/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/guitar.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.24, 0.24, 0.24]}>
        <mesh material={materials.Gray} geometry={nodes.pCube10.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube11.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube12.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube13.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube14.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube15.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube16.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube17.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube18.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube19.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube20.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube21.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube22.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube23.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube24.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube25.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube26.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube27.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube28.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube7.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube8.geometry} />
        <mesh material={materials.Gray} geometry={nodes.pCube9.geometry} />
        <mesh material={materials.White} geometry={nodes.pCube29.geometry} />
        <mesh material={materials.White} geometry={nodes.pCube30.geometry} />
        <mesh material={materials.White} geometry={nodes.pCube31.geometry} />
        <mesh material={materials.White} geometry={nodes.pCube32.geometry} />
        <mesh material={materials.White} geometry={nodes.pCube33.geometry} />
        <mesh material={materials.White} geometry={nodes.pCube34.geometry} />
        <mesh material={materials.White} geometry={nodes.pCube35.geometry} />
        <mesh material={materials.White} geometry={nodes.pCube36.geometry} />
        <mesh material={materials.White} geometry={nodes.pCube37.geometry} />
        <mesh material={materials.White} geometry={nodes.pCube38.geometry} />
        <mesh
          material={materials['Brown.001']}
          geometry={nodes.EbonyFingerboard.geometry}
        />
        <mesh material={materials['Black.001']} geometry={nodes.Nut.geometry} />
        <mesh
          material={materials.White}
          geometry={nodes.OptionalFingerboard.geometry}
        />
        <mesh material={materials.Red} geometry={nodes.Neck.geometry} />
        <mesh material={materials.Red} geometry={nodes.pCube2.geometry} />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCube46.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.Switch.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.SwitchBase.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.Tone.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.Tone2.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.Volume.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCube43.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCube44.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCube47.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCube48.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder10.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder11.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder12.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder7.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder8.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder9.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.Bridge.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pSphere1.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pSphere2.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pSphere3.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pSphere4.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pSphere5.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pSphere6.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder20002.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder21002.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder22002.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder20003.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder21003.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder22003.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder20004.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder21004.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder22004.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder20005.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder21005.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder22005.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder20.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder21.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder22.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder20001.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder21001.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.pCylinder22001.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.Cover.geometry}
        />
        <mesh
          material={materials['Black.001']}
          geometry={nodes.Headline.geometry}
        />
        <mesh
          material={materials.White}
          geometry={nodes.pCylinder14.geometry}
        />
        <mesh
          material={materials.White}
          geometry={nodes.pCylinder15.geometry}
        />
        <mesh
          material={materials.White}
          geometry={nodes.pCylinder16.geometry}
        />
        <mesh
          material={materials.White}
          geometry={nodes.pCylinder17.geometry}
        />
        <mesh
          material={materials.White}
          geometry={nodes.pCylinder18.geometry}
        />
        <mesh
          material={materials.White}
          geometry={nodes.pCylinder19.geometry}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/guitar.glb')
